# Pathfinding/dijkstra.py

import heapq
import itertools
import math

from .heuristics import (
    lnd_cost,
    modified_cost,
    adaptive_heuristic,
)

from Network.topology import geo_features


class Dijkstra:
    """
    Dijkstra-based routing engine for a Lightning-style
    payment network.

    Routing pipeline:

        Network State
              |
              v
             PPO
              |
              v
             eta
              |
              v
      Adaptive Heuristic
              |
              v
       Modified Edge Cost
              |
              v
           Dijkstra
              |
              v
        Candidate Route
              |
              v
      Payment Simulation
              |
              v
          Feedback
              |
              v
      Learned Channel State

    Important:
        capacity != balance
        capacity != liquidity
        capacity != available payment amount

    The raw GML snapshot does not provide directional
    liquidity. Therefore capacity is never interpreted as
    liquidity or balance.

    If estimated/observed directional liquidity exists,
    it can be used as a feasibility constraint.

    If liquidity is unknown, the channel is not rejected
    merely because liquidity is unavailable.
    """

    def __init__(self, graph):
        self.G = graph

    # ========================================================
    # Main Routing
    # ========================================================

    def shortest_path(
        self,
        source,
        target,
        amount,
        heuristic_fn=None,
        eta=0.0,
        max_hops=12,
        lambda_h=1.0,
    ):
        """
        Find a minimum-cost feasible path.

        Parameters
        ----------
        source : node
            Source node.

        target : node
            Destination node.

        amount : float
            Payment amount.

        heuristic_fn : callable, optional
            Native routing cost function.

            If omitted, lnd_cost is used.

        eta : float
            Adaptive routing coefficient generated by PPO.

            -1 <= eta <= 1

        max_hops : int
            Maximum number of hops.

        lambda_h : float
            Weight of adaptive heuristic.

        Returns
        -------
        dict
            Standardized routing result.
        """

        # ----------------------------------------------------
        # Validate source
        # ----------------------------------------------------

        if source not in self.G:
            raise ValueError(
                f"Unknown source node: {source}"
            )

        # ----------------------------------------------------
        # Validate target
        # ----------------------------------------------------

        if target not in self.G:
            raise ValueError(
                f"Unknown target node: {target}"
            )

        if source == target:
            return self._failure(
                "source_equals_target"
            )

        # ----------------------------------------------------
        # Validate amount
        # ----------------------------------------------------

        try:
            amount = float(amount)
        except (
            TypeError,
            ValueError,
        ):
            raise ValueError(
                "amount must be numeric"
            )

        if (
            not math.isfinite(amount)
            or
            amount <= 0.0
        ):
            raise ValueError(
                "amount must be finite and greater than zero"
            )

        # ----------------------------------------------------
        # Validate max_hops
        # ----------------------------------------------------

        try:
            max_hops = int(max_hops)
        except (
            TypeError,
            ValueError,
        ):
            raise ValueError(
                "max_hops must be an integer"
            )

        if max_hops <= 0:
            raise ValueError(
                "max_hops must be greater than zero"
            )

        # ----------------------------------------------------
        # Validate eta
        # ----------------------------------------------------

        try:
            eta = float(eta)
        except (
            TypeError,
            ValueError,
        ):
            raise ValueError(
                "eta must be numeric"
            )

        if not math.isfinite(eta):
            raise ValueError(
                "eta must be finite"
            )

        if not -1.0 <= eta <= 1.0:
            raise ValueError(
                "eta must satisfy -1 <= eta <= 1"
            )

        # ----------------------------------------------------
        # Validate lambda_h
        # ----------------------------------------------------

        try:
            lambda_h = float(lambda_h)
        except (
            TypeError,
            ValueError,
        ):
            raise ValueError(
                "lambda_h must be numeric"
            )

        if (
            not math.isfinite(lambda_h)
            or
            lambda_h < 0.0
        ):
            raise ValueError(
                "lambda_h must be finite and >= 0"
            )

        # ----------------------------------------------------
        # Node availability
        # ----------------------------------------------------

        if not self._node_online(source):
            return self._failure(
                "source_offline"
            )

        if not self._node_online(target):
            return self._failure(
                "target_offline"
            )

        # ====================================================
        # Priority Queue
        # ====================================================

        counter = itertools.count()

        pq = []

        heapq.heappush(
            pq,
            (
                0.0,          # cost
                0,             # hops
                next(counter),
                source,
                (source,),
                (),
                0.0,          # fee
                0.0,          # delay
                1.0,          # reliability
                0.0,          # distance
                0.0,          # carbon
                0,             # inter-country hops
                0,             # inter-continent hops
            )
        )

        # ====================================================
        # Dominance table
        # ====================================================

        best = {}

        # ====================================================
        # Dijkstra Search
        # ====================================================

        while pq:

            (
                cost,
                hops,
                _counter,
                u,
                path,
                edges,
                total_fee,
                total_delay,
                path_reliability,
                total_distance,
                total_carbon,
                inter_country_hops,
                inter_continent_hops,
            ) = heapq.heappop(pq)

            # ------------------------------------------------
            # Destination
            # ------------------------------------------------

            if u == target:

                return self._success(
                    path=path,
                    edges=edges,
                    cost=cost,
                    hop_count=hops,
                    total_fee=total_fee,
                    total_delay=total_delay,
                    path_reliability=path_reliability,
                    total_distance=total_distance,
                    total_carbon=total_carbon,
                    inter_country_hops=inter_country_hops,
                    inter_continent_hops=inter_continent_hops,
                    eta=eta,
                    lambda_h=lambda_h,
                )

            # ------------------------------------------------
            # Hop limit
            # ------------------------------------------------

            if hops >= max_hops:
                continue

            # ------------------------------------------------
            # Dominance check
            #
            # A state is identified by:
            #
            #     (node, hop_count)
            #
            # A more expensive state is discarded.
            # ------------------------------------------------

            state = (
                u,
                hops,
            )

            previous_best = best.get(
                state,
                math.inf,
            )

            if cost >= previous_best:
                continue

            best[state] = cost

            # =================================================
            # Explore outgoing channels
            # =================================================

            for v, channel_dict in self.G[u].items():

                # ------------------------------------------------
                # Prevent node loops
                # ------------------------------------------------

                if v in path:
                    continue

                # ------------------------------------------------
                # Destination / intermediate node availability
                # ------------------------------------------------

                if not self._node_online(v):
                    continue

                # =================================================
                # MultiDiGraph / parallel channels
                # =================================================

                if self._is_multigraph():

                    channel_items = (
                        channel_dict.items()
                    )

                else:

                    channel_items = [
                        (
                            channel_dict.get(
                                "channel_key",
                                None
                            ),
                            channel_dict
                        )
                    ]

                # =================================================
                # Evaluate every usable channel
                # =================================================

                for key, raw_data in channel_items:

                    data = dict(
                        raw_data
                    )

                    # ------------------------------------------------
                    # Normalize without modifying G
                    # ------------------------------------------------

                    self._normalize_edge_data(
                        data
                    )

                    # ------------------------------------------------
                    # Channel availability
                    # ------------------------------------------------

                    if not self._channel_available(
                        data
                    ):
                        continue

                    # ------------------------------------------------
                    # Directional liquidity
                    # ------------------------------------------------

                    liquidity = (
                        self._estimated_liquidity(
                            data
                        )
                    )

                    if (
                        liquidity is not None
                        and
                        liquidity < amount
                    ):
                        continue

                    # =================================================
                    # Native LND cost
                    # =================================================

                    if heuristic_fn is None:
                        native_cost_fn = lnd_cost
                    else:
                        native_cost_fn = heuristic_fn

                    try:

                        native_cost = native_cost_fn(
                            self.G,
                            u,
                            v,
                            data,
                            amount,
                        )

                    except (
                        TypeError,
                        ValueError,
                        KeyError,
                        AttributeError,
                    ):

                        # If custom heuristic fails, fall back
                        # to native LND cost.
                        if heuristic_fn is not None:

                            try:

                                native_cost = lnd_cost(
                                    self.G,
                                    u,
                                    v,
                                    data,
                                    amount,
                                )

                            except Exception:
                                continue

                        else:
                            continue

                    if not self._valid_cost(
                        native_cost
                    ):
                        continue

                    native_cost = float(
                        native_cost
                    )

                    # =================================================
                    # Adaptive heuristic
                    # =================================================

                    try:

                        adaptive_h = adaptive_heuristic(
                            self.G,
                            u,
                            v,
                            eta,
                        )

                    except (
                        TypeError,
                        ValueError,
                        KeyError,
                        AttributeError,
                    ):

                        adaptive_h = 0.0

                    if not self._valid_number(
                        adaptive_h
                    ):
                        continue

                    adaptive_h = float(
                        adaptive_h
                    )

                    # =================================================
                    # Modified cost
                    # =================================================

                    try:

                        edge_cost = modified_cost(
                            native_cost=native_cost,
                            geo_penalty=adaptive_h,
                            eta=eta,
                            lambda_h=lambda_h,
                        )

                    except TypeError:

                        # Backward-compatible call in case the
                        # current heuristics.py uses positional args.
                        try:

                            edge_cost = modified_cost(
                                native_cost,
                                adaptive_h,
                                eta,
                            )

                        except Exception:
                            continue

                    except (
                        ValueError,
                        KeyError,
                        AttributeError,
                    ):
                        continue

                    if not self._valid_cost(
                        edge_cost
                    ):
                        continue

                    edge_cost = float(
                        edge_cost
                    )

                    # =================================================
                    # Channel fee
                    # =================================================

                    fee = self._channel_fee(
                        data,
                        amount,
                    )

                    if not self._valid_metric(
                        fee
                    ):
                        continue

                    # =================================================
                    # Delay
                    # =================================================

                    delay = self._channel_delay(
                        data
                    )

                    if not self._valid_metric(
                        delay
                    ):
                        continue

                    # =================================================
                    # Reliability
                    # =================================================

                    failure_probability = (
                        self._failure_probability(
                            data
                        )
                    )

                    channel_reliability = (
                        1.0
                        -
                        failure_probability
                    )

                    new_reliability = (
                        path_reliability
                        *
                        channel_reliability
                    )

                    # =================================================
                    # Geographic metrics
                    # =================================================

                    (
                        distance_km,
                        carbon_intensity,
                        inter_country,
                        inter_continent,
                    ) = self._geographic_metrics(
                        u,
                        v,
                        data,
                    )

                    # =================================================
                    # Accumulate
                    # =================================================

                    new_cost = (
                        cost
                        +
                        edge_cost
                    )

                    new_hops = (
                        hops
                        +
                        1
                    )

                    if new_hops > max_hops:
                        continue

                    new_fee = (
                        total_fee
                        +
                        fee
                    )

                    new_delay = (
                        total_delay
                        +
                        delay
                    )

                    new_distance = (
                        total_distance
                        +
                        distance_km
                    )

                    new_carbon = (
                        total_carbon
                        +
                        carbon_intensity
                    )

                    new_inter_country = (
                        inter_country_hops
                        +
                        int(inter_country)
                    )

                    new_inter_continent = (
                        inter_continent_hops
                        +
                        int(inter_continent)
                    )

                    # =================================================
                    # Push next state
                    # =================================================

                    heapq.heappush(
                        pq,
                        (
                            new_cost,
                            new_hops,
                            next(counter),
                            v,
                            path + (v,),
                            edges + (
                                (
                                    u,
                                    v,
                                    key,
                                ),
                            ),
                            new_fee,
                            new_delay,
                            new_reliability,
                            new_distance,
                            new_carbon,
                            new_inter_country,
                            new_inter_continent,
                        )
                    )

        # ====================================================
        # No feasible route
        # ====================================================

        return self._failure(
            "no_feasible_path"
        )

    # ========================================================
    # Graph Type
    # ========================================================

    def _is_multigraph(self):
        """
        Return True for MultiGraph / MultiDiGraph.
        """

        return isinstance(
            self.G,
            (
                __import__(
                    "networkx"
                ).MultiGraph,
                __import__(
                    "networkx"
                ).MultiDiGraph,
            )
        )

    # ========================================================
    # Edge Normalization
    # ========================================================

    @staticmethod
    def _normalize_edge_data(data):
        """
        Normalize raw Lightning/GML channel attributes.

        capacity is preserved exactly.

        No balance or liquidity is inferred from capacity.
        """

        # ----------------------------------------------------
        # Base fee
        # ----------------------------------------------------

        if "fee_base" not in data:

            data["fee_base"] = (
                Dijkstra._safe_float(
                    data.get(
                        "fee_base_msat",
                        0.0,
                    )
                )
            )

        # ----------------------------------------------------
        # Proportional fee
        # ----------------------------------------------------

        if "fee_rate" not in data:

            data["fee_rate"] = (
                Dijkstra._safe_float(
                    data.get(
                        "fee_proportional_millionths",
                        0.0,
                    )
                )
            )

        # ----------------------------------------------------
        # Delay
        # ----------------------------------------------------

        if "delay" not in data:

            data["delay"] = (
                Dijkstra._safe_float(
                    data.get(
                        "cltv_expiry_delta",
                        0.0,
                    )
                )
            )

        # ----------------------------------------------------
        # Availability
        # ----------------------------------------------------

        if "available" not in data:

            data["available"] = True

        # ----------------------------------------------------
        # Statistics
        # ----------------------------------------------------

        if "failure_count" not in data:

            data["failure_count"] = 0

        if "success_count" not in data:

            data["success_count"] = 0

    # ========================================================
    # Directional Liquidity
    # ========================================================

    @staticmethod
    def _estimated_liquidity(data):
        """
        Return known directional liquidity.

        Priority:

            1. estimated_liquidity
            2. liquidity_uv
            3. balance_uv

        If unavailable:

            None

        capacity is NEVER used as liquidity.
        """

        for field in (
            "estimated_liquidity",
            "liquidity_uv",
            "balance_uv",
        ):

            if field not in data:
                continue

            value = data.get(
                field
            )

            if value is None:
                continue

            try:
                value = float(value)
            except (
                TypeError,
                ValueError,
            ):
                continue

            if (
                math.isfinite(value)
                and
                value >= 0.0
            ):
                return value

        return None

    # ========================================================
    # Node Availability
    # ========================================================

    def _node_online(self, node):
        """
        Support both:

            available
            is_online
            online

        Missing status is interpreted as available.
        """

        if node not in self.G:
            return False

        data = self.G.nodes[node]

        if not bool(
            data.get(
                "available",
                True,
            )
        ):
            return False

        if not bool(
            data.get(
                "is_online",
                True,
            )
        ):
            return False

        if not bool(
            data.get(
                "online",
                True,
            )
        ):
            return False

        return True

    # ========================================================
    # Channel Availability
    # ========================================================

    @staticmethod
    def _channel_available(data):
        return bool(
            data.get(
                "available",
                True,
            )
        )

    # ========================================================
    # Channel Fee
    # ========================================================

    @staticmethod
    def _channel_fee(data, amount):
        """
        Calculate forwarding fee.

        Formula:

            fee =
                base_fee
                +
                amount * fee_rate / 1,000,000

        fee_rate is interpreted as PPM.
        """

        base_fee = Dijkstra._safe_float(
            data.get(
                "fee_base",
                data.get(
                    "fee_base_msat",
                    0.0,
                ),
            )
        )

        fee_rate = Dijkstra._safe_float(
            data.get(
                "fee_rate",
                data.get(
                    "fee_proportional_millionths",
                    0.0,
                ),
            )
        )

        return (
            base_fee
            +
            (
                amount
                *
                fee_rate
                /
                1_000_000.0
            )
        )

    # ========================================================
    # Channel Delay
    # ========================================================

    @staticmethod
    def _channel_delay(data):
        return Dijkstra._safe_float(
            data.get(
                "delay",
                data.get(
                    "cltv_expiry_delta",
                    0.0,
                ),
            )
        )

    # ========================================================
    # Failure Probability
    # ========================================================

    @staticmethod
    def _failure_probability(data):
        """
        Estimate channel forwarding failure probability.

        If historical success/failure statistics exist,
        they have priority.

        Otherwise failure_probability is used.

        If no information exists, the default is 0.01.
        """

        success = Dijkstra._safe_float(
            data.get(
                "success_count",
                0,
            )
        )

        failure = Dijkstra._safe_float(
            data.get(
                "failure_count",
                0,
            )
        )

        total = success + failure

        if total > 0.0:

            probability = (
                failure
                /
                total
            )

        elif "failure_probability" in data:

            probability = Dijkstra._safe_float(
                data.get(
                    "failure_probability"
                ),
                default=0.01,
            )

        else:

            probability = 0.01

        return min(
            max(
                probability,
                0.0,
            ),
            1.0,
        )

    # ========================================================
    # Geographic Metrics
    # ========================================================

    def _geographic_metrics(
        self,
        u,
        v,
        data,
    ):
        """
        Extract geographic metrics from Network.topology.

        Expected values:

            distance_km
            carbon_intensity
            inter_country
            inter_continent
        """

        try:

            features = geo_features(
                self.G,
                u,
                v,
            )

            distance = self._safe_float(
                features.get(
                    "distance_km",
                    0.0,
                )
            )

            carbon = self._safe_float(
                features.get(
                    "carbon_intensity",
                    0.0,
                )
            )

            inter_country = int(
                bool(
                    features.get(
                        "inter_country",
                        False,
                    )
                )
            )

            inter_continent = int(
                bool(
                    features.get(
                        "inter_continent",
                        False,
                    )
                )
            )

            return (
                distance,
                carbon,
                inter_country,
                inter_continent,
            )

        except (
            KeyError,
            TypeError,
            ValueError,
            AttributeError,
        ):

            return (
                0.0,
                0.0,
                0,
                0,
            )

    # ========================================================
    # Minimum Known Liquidity
    # ========================================================

    def _minimum_liquidity(self, edges):
        """
        Return minimum known directional liquidity.

        Unknown liquidity is ignored.

        If all channels have unknown liquidity:

            None
        """

        if not edges:
            return None

        values = []

        for u, v, key in edges:

            try:

                if key is None:

                    data = self.G[u][v]

                else:

                    data = self.G[u][v][key]

            except (
                KeyError,
                TypeError,
            ):
                continue

            liquidity = (
                self._estimated_liquidity(
                    data
                )
            )

            if liquidity is not None:
                values.append(
                    liquidity
                )

        if not values:
            return None

        return min(values)

    # ========================================================
    # Success Result
    # ========================================================

    def _success(
        self,
        path,
        edges,
        cost,
        hop_count,
        total_fee,
        total_delay,
        path_reliability,
        total_distance,
        total_carbon,
        inter_country_hops,
        inter_continent_hops,
        eta=0.0,
        lambda_h=1.0,
    ):
        """
        Standardized successful routing result.
        """

        min_liquidity = (
            self._minimum_liquidity(
                edges
            )
        )

        return {

            "success": True,

            "path": list(
                path
            ),

            "edges": list(
                edges
            ),

            "cost": float(
                cost
            ),

            "hop_count": int(
                hop_count
            ),

            "total_fee": float(
                total_fee
            ),

            "total_delay": float(
                total_delay
            ),

            "min_liquidity": (
                None
                if min_liquidity is None
                else float(
                    min_liquidity
                )
            ),

            "reliability": float(
                path_reliability
            ),

            "failure_probability": float(
                1.0
                -
                path_reliability
            ),

            "total_distance_km": float(
                total_distance
            ),

            "total_carbon": float(
                total_carbon
            ),

            "inter_country_hops": int(
                inter_country_hops
            ),

            "inter_continent_hops": int(
                inter_continent_hops
            ),

            "eta": float(
                eta
            ),

            "lambda_h": float(
                lambda_h
            ),

            "candidate": True,

            "reason": None,
        }

    # ========================================================
    # Failure Result
    # ========================================================

    @staticmethod
    def _failure(
        reason="no_feasible_path"
    ):
        """
        Standardized routing failure.

        This represents a routing-layer failure.

        It is different from a stochastic payment failure
        reported by FailureModel / PaymentSimulator.
        """

        return {

            "success": False,

            "path": None,

            "edges": None,

            "cost": math.inf,

            "hop_count": 0,

            "total_fee": 0.0,

            "total_delay": 0.0,

            "min_liquidity": None,

            "reliability": 0.0,

            "failure_probability": 1.0,

            "total_distance_km": 0.0,

            "total_carbon": 0.0,

            "inter_country_hops": 0,

            "inter_continent_hops": 0,

            "eta": None,

            "lambda_h": None,

            "candidate": False,

            "reason": reason,
        }

    # ========================================================
    # Numeric Helpers
    # ========================================================

    @staticmethod
    def _safe_float(
        value,
        default=0.0,
    ):
        try:

            value = float(value)

            if not math.isfinite(value):
                return float(default)

            return value

        except (
            TypeError,
            ValueError,
        ):
            return float(default)

    @staticmethod
    def _valid_number(value):
        try:

            value = float(value)

            return math.isfinite(value)

        except (
            TypeError,
            ValueError,
        ):
            return False

    @staticmethod
    def _valid_metric(value):
        try:

            value = float(value)

            return (
                math.isfinite(value)
                and
                value >= 0.0
            )

        except (
            TypeError,
            ValueError,
        ):
            return False

    @staticmethod
    def _valid_cost(value):
        """
        Dijkstra requires finite non-negative edge costs.
        """

        try:

            value = float(value)

            return (
                math.isfinite(value)
                and
                value >= 0.0
            )

        except (
            TypeError,
            ValueError,
        ):
            return False