# Pathfinding/dijkstra.py

import heapq
import itertools
import math

from .heuristics import (
    modified_cost,
    adaptive_heuristic,
)

from Network.topology import geo_features


class Dijkstra:
    """
    Dijkstra-based routing engine for a Lightning-style
    payment network.

    The routing model separates:

        1. Static topology information
        2. Channel policy information
        3. Learned / observed channel state
        4. Adaptive routing information generated by PPO

    Important distinction
    ---------------------

    capacity != balance
    capacity != liquidity
    capacity != available payment amount

    The raw GML snapshot does not provide directional channel
    balance. Therefore, capacity is NEVER converted into
    liquidity or balance.

    If learned/observed directional liquidity is available,
    it may be used as a feasibility constraint.

    Otherwise, liquidity is considered unknown and the route
    is not rejected merely because liquidity is unknown.

    Routing pipeline:

        State
          |
          v
        PPO
          |
          v
        eta
          |
          v
    Adaptive Heuristic
          |
          v
    Modified Cost
          |
          v
        Dijkstra
          |
          v
    Candidate Path
          |
          v
    Payment Simulation
          |
          v
       Feedback
          |
          v
    Learned Channel State
    """

    def __init__(self, graph):
        self.G = graph

    # ========================================================
    # Main Routing
    # ========================================================

    def shortest_path(
        self,
        source,
        target,
        amount,
        heuristic_fn,
        eta=0.0,
        max_hops=12
    ):
        """
        Find a minimum-cost feasible path.

        Parameters
        ----------
        source : node
            Source node.

        target : node
            Destination node.

        amount : float
            Payment amount.

        heuristic_fn : callable
            Native routing cost function:

                heuristic_fn(
                    G,
                    u,
                    v,
                    data,
                    amount
                )

        eta : float
            Adaptive routing coefficient generated by PPO.

            -1 <= eta <= 1

        max_hops : int
            Maximum number of hops.

        Returns
        -------
        dict
            Standardized routing result.
        """

        # ----------------------------------------------------
        # Validate source / target
        # ----------------------------------------------------

        if source not in self.G:
            raise ValueError(
                f"Unknown source node: {source}"
            )

        if target not in self.G:
            raise ValueError(
                f"Unknown target node: {target}"
            )

        if source == target:
            return self._failure(
                "source_equals_target"
            )

        # ----------------------------------------------------
        # Validate amount
        # ----------------------------------------------------

        amount = self._safe_float(
            amount,
            default=-1.0
        )

        if amount <= 0:
            raise ValueError(
                "amount must be greater than zero"
            )

        # ----------------------------------------------------
        # Validate max_hops
        # ----------------------------------------------------

        if not isinstance(
            max_hops,
            int
        ):
            raise ValueError(
                "max_hops must be an integer"
            )

        if max_hops <= 0:
            raise ValueError(
                "max_hops must be greater than zero"
            )

        # ----------------------------------------------------
        # Validate eta
        # ----------------------------------------------------

        eta = self._safe_float(
            eta,
            default=0.0
        )

        if eta < -1.0 or eta > 1.0:
            raise ValueError(
                "eta must satisfy -1 <= eta <= 1"
            )

        # ----------------------------------------------------
        # Node availability
        # ----------------------------------------------------

        if not self._node_online(source):
            return self._failure(
                "source_offline"
            )

        if not self._node_online(target):
            return self._failure(
                "target_offline"
            )

        # ====================================================
        # Priority Queue
        # ====================================================

        pq = []

        counter = itertools.count()

        heapq.heappush(
            pq,
            (
                0.0,                  # cost
                0,                     # hops
                next(counter),        # tie breaker
                source,                # node
                (source,),             # path
                (),                    # edges
                0.0,                  # fee
                0.0,                  # delay
                1.0,                  # reliability
                0.0,                  # distance
                0.0,                  # carbon
                0,                     # country hops
                0                      # continent hops
            )
        )

        # ----------------------------------------------------
        # Best cost for (node, hop_count)
        # ----------------------------------------------------

        best = {}

        # ====================================================
        # Dijkstra Search
        # ====================================================

        while pq:

            (
                cost,
                hops,
                _counter,
                u,
                path,
                edges,
                total_fee,
                total_delay,
                path_reliability,
                total_distance,
                total_carbon,
                inter_country_hops,
                inter_continent_hops
            ) = heapq.heappop(
                pq
            )

            # ------------------------------------------------
            # Destination
            # ------------------------------------------------

            if u == target:

                return self._success(
                    path=path,
                    edges=edges,
                    cost=cost,
                    hop_count=hops,
                    total_fee=total_fee,
                    total_delay=total_delay,
                    path_reliability=path_reliability,
                    total_distance=total_distance,
                    total_carbon=total_carbon,
                    inter_country_hops=inter_country_hops,
                    inter_continent_hops=inter_continent_hops
                )

            # ------------------------------------------------
            # Hop limit
            # ------------------------------------------------

            if hops >= max_hops:
                continue

            # ------------------------------------------------
            # Dominance check
            # ------------------------------------------------

            state = (
                u,
                hops
            )

            previous_best = best.get(
                state,
                math.inf
            )

            if cost >= previous_best:
                continue

            best[state] = cost

            # =================================================
            # Explore outgoing neighbors
            # =================================================

            for v, channel_dict in self.G[u].items():

                # ------------------------------------------------
                # Prevent loops
                # ------------------------------------------------

                if v in path:
                    continue

                # ------------------------------------------------
                # Destination node must be online
                # ------------------------------------------------

                if not self._node_online(v):
                    continue

                # =================================================
                # Parallel channels
                # =================================================

                for key, raw_data in channel_dict.items():

                    # ------------------------------------------------
                    # Work on a copy.
                    #
                    # This prevents Dijkstra from modifying the
                    # original graph simply by normalizing fields.
                    # ------------------------------------------------

                    data = dict(
                        raw_data
                    )

                    self._normalize_edge_data(
                        data
                    )

                    # ------------------------------------------------
                    # Channel availability
                    # ------------------------------------------------

                    if not self._channel_available(
                        data
                    ):
                        continue

                    # ------------------------------------------------
                    # Learned liquidity
                    #
                    # None means unknown.
                    #
                    # Unknown != zero.
                    #
                    # capacity is never used.
                    # ------------------------------------------------

                    estimated_liquidity = (
                        self._estimated_liquidity(
                            data
                        )
                    )

                    if (
                        estimated_liquidity is not None
                        and
                        estimated_liquidity < amount
                    ):
                        continue

                    # =================================================
                    # Native routing cost
                    # =================================================

                    try:

                        native_cost = heuristic_fn(
                            self.G,
                            u,
                            v,
                            data,
                            amount
                        )

                    except Exception:
                        continue

                    if not self._valid_cost(
                        native_cost
                    ):
                        continue

                    native_cost = float(
                        native_cost
                    )

                    # =================================================
                    # Adaptive heuristic
                    #
                    # README formulation:
                    #
                    # h(u,v) =
                    #
                    # eta * ((C_u + C_v) / 2)
                    #
                    # +
                    #
                    # (1 - eta) * (C_v - C_u)
                    #
                    # where C is carbon intensity.
                    # =================================================

                    try:

                        adaptive_h = adaptive_heuristic(
                            self.G,
                            u,
                            v,
                            eta
                        )

                    except Exception:

                        adaptive_h = 0.0

                    if not self._valid_number(
                        adaptive_h
                    ):
                        continue

                    adaptive_h = float(
                        adaptive_h
                    )

                    # =================================================
                    # Modified routing cost
                    # =================================================

                    try:

                        edge_cost = modified_cost(
                            native_cost,
                            adaptive_h,
                            eta
                        )

                    except Exception:

                        continue

                    if not self._valid_cost(
                        edge_cost
                    ):
                        continue

                    edge_cost = float(
                        edge_cost
                    )

                    # =================================================
                    # Fee
                    # =================================================

                    fee = self._channel_fee(
                        data,
                        amount
                    )

                    if not self._valid_metric(
                        fee
                    ):
                        continue

                    # =================================================
                    # Delay
                    # =================================================

                    delay = self._channel_delay(
                        data
                    )

                    if not self._valid_metric(
                        delay
                    ):
                        continue

                    # =================================================
                    # Reliability
                    # =================================================

                    failure_probability = (
                        self._failure_probability(
                            data
                        )
                    )

                    channel_reliability = (
                        1.0
                        -
                        failure_probability
                    )

                    new_reliability = (
                        path_reliability
                        *
                        channel_reliability
                    )

                    # =================================================
                    # Geographic metrics
                    # =================================================

                    (
                        distance_km,
                        carbon_intensity,
                        inter_country,
                        inter_continent
                    ) = self._geographic_metrics(
                        u,
                        v,
                        data
                    )

                    # =================================================
                    # Accumulate
                    # =================================================

                    new_cost = (
                        cost
                        +
                        edge_cost
                    )

                    new_hops = (
                        hops
                        +
                        1
                    )

                    new_fee = (
                        total_fee
                        +
                        fee
                    )

                    new_delay = (
                        total_delay
                        +
                        delay
                    )

                    new_distance = (
                        total_distance
                        +
                        distance_km
                    )

                    new_carbon = (
                        total_carbon
                        +
                        carbon_intensity
                    )

                    new_inter_country = (
                        inter_country_hops
                        +
                        int(inter_country)
                    )

                    new_inter_continent = (
                        inter_continent_hops
                        +
                        int(inter_continent)
                    )

                    # =================================================
                    # Push state
                    # =================================================

                    heapq.heappush(
                        pq,
                        (
                            new_cost,
                            new_hops,
                            next(counter),
                            v,
                            path + (v,),
                            edges + (
                                (
                                    u,
                                    v,
                                    key
                                ),
                            ),
                            new_fee,
                            new_delay,
                            new_reliability,
                            new_distance,
                            new_carbon,
                            new_inter_country,
                            new_inter_continent
                        )
                    )

        # ====================================================
        # No route
        # ====================================================

        return self._failure(
            "no_feasible_path"
        )

    # ========================================================
    # Edge Normalization
    # ========================================================

    @staticmethod
    def _normalize_edge_data(
        data
    ):
        """
        Normalize raw GML channel attributes.

        IMPORTANT:

        capacity is preserved exactly as channel capacity.

        No balance or liquidity is inferred from capacity.
        """

        # ----------------------------------------------------
        # Base fee
        # ----------------------------------------------------

        if "fee_base" not in data:

            data["fee_base"] = (
                Dijkstra._safe_float(
                    data.get(
                        "fee_base_msat",
                        0.0
                    )
                )
            )

        # ----------------------------------------------------
        # Proportional fee
        # ----------------------------------------------------

        if "fee_rate" not in data:

            data["fee_rate"] = (
                Dijkstra._safe_float(
                    data.get(
                        "fee_proportional_millionths",
                        0.0
                    )
                )

            )

        # ----------------------------------------------------
        # Delay
        # ----------------------------------------------------

        if "delay" not in data:

            data["delay"] = (
                Dijkstra._safe_float(
                    data.get(
                        "cltv_expiry_delta",
                        0.0
                    )
                )
            )

        # ----------------------------------------------------
        # Availability
        # ----------------------------------------------------

        if "available" not in data:

            data["available"] = True

        # ----------------------------------------------------
        # Experience statistics
        # ----------------------------------------------------

        if "failure_count" not in data:

            data["failure_count"] = 0

        if "success_count" not in data:

            data["success_count"] = 0

    # ========================================================
    # Liquidity
    # ========================================================

    @staticmethod
    def _estimated_liquidity(
        data
    ):
        """
        Return learned/observed directional liquidity.

        Priority:

            estimated_liquidity
            liquidity_uv
            balance_uv

        If unavailable:

            None

        capacity is NEVER used.
        """

        for field in (
            "estimated_liquidity",
            "liquidity_uv",
            "balance_uv"
        ):

            if field not in data:
                continue

            value = Dijkstra._safe_float(
                data[field],
                default=-1.0
            )

            if value >= 0.0:

                return value

        return None

    # ========================================================
    # Node Status
    # ========================================================

    def _node_online(
        self,
        node
    ):
        """
        If online information is absent,
        assume the node is usable.
        """

        return bool(
            self.G.nodes[node].get(
                "online",
                True
            )
        )

    # ========================================================
    # Channel Status
    # ========================================================

    @staticmethod
    def _channel_available(
        data
    ):
        return bool(
            data.get(
                "available",
                True
            )
        )

    # ========================================================
    # Channel Fee
    # ========================================================

    @staticmethod
    def _channel_fee(
        data,
        amount
    ):
        """
        Calculate forwarding fee.

        Formula:

            fee =
                base
                +
                amount * rate / 1,000,000

        rate is PPM.

        NOTE:
        Unit consistency between amount and fee_base_msat
        must be handled consistently by the caller/simulator.
        """

        base_fee = Dijkstra._safe_float(
            data.get(
                "fee_base",
                data.get(
                    "fee_base_msat",
                    0.0
                )
            )
        )

        fee_rate = Dijkstra._safe_float(
            data.get(
                "fee_rate",
                data.get(
                    "fee_proportional_millionths",
                    0.0
                )
            )
        )

        return (
            base_fee
            +
            (
                amount
                *
                fee_rate
                /
                1_000_000.0
            )
        )

    # ========================================================
    # Channel Delay
    # ========================================================

    @staticmethod
    def _channel_delay(
        data
    ):
        return Dijkstra._safe_float(
            data.get(
                "delay",
                data.get(
                    "cltv_expiry_delta",
                    0.0
                )
            )
        )

    # ========================================================
    # Failure Probability
    # ========================================================

    @staticmethod
    def _failure_probability(
        data
    ):
        """
        Estimate forwarding failure probability.

        Experience has priority over the initial/default
        estimate.
        """

        success = Dijkstra._safe_float(
            data.get(
                "success_count",
                0
            )
        )

        failure = Dijkstra._safe_float(
            data.get(
                "failure_count",
                0
            )
        )

        total = (
            success
            +
            failure
        )

        if total > 0:

            probability = (
                failure
                /
                total
            )

        elif "failure_probability" in data:

            probability = Dijkstra._safe_float(
                data[
                    "failure_probability"
                ]
            )

        else:

            probability = 0.01

        return min(
            max(
                probability,
                0.0
            ),
            1.0
        )

    # ========================================================
    # Geographic Metrics
    # ========================================================

    def _geographic_metrics(
        self,
        u,
        v,
        data
    ):
        """
        Extract geographic metrics.

        carbon_intensity is expected to originate from
        rgb_color when real snapshot data are used.
        """

        try:

            features = geo_features(
                self.G,
                u,
                v
            )

            distance = self._safe_float(
                features.get(
                    "distance_km",
                    0.0
                )
            )

            carbon = self._safe_float(
                features.get(
                    "carbon_intensity",
                    0.0
                )
            )

            inter_country = int(
                bool(
                    features.get(
                        "inter_country",
                        False
                    )
                )
            )

            inter_continent = int(
                bool(
                    features.get(
                        "inter_continent",
                        False
                    )
                )
            )

            return (
                distance,
                carbon,
                inter_country,
                inter_continent
            )

        except (
            KeyError,
            TypeError,
            ValueError,
            AttributeError
        ):

            return (
                0.0,
                0.0,
                0,
                0
            )

    # ========================================================
    # Minimum Known Liquidity
    # ========================================================

    def _minimum_liquidity(
        self,
        edges
    ):
        """
        Return minimum known directional liquidity.

        Unknown liquidity is ignored.

        If all channels are unknown:

            None
        """

        if not edges:
            return None

        values = []

        for u, v, key in edges:

            try:

                data = self.G[u][v][key]

            except (
                KeyError,
                TypeError
            ):

                continue

            liquidity = (
                self._estimated_liquidity(
                    data
                )
            )

            if liquidity is not None:

                values.append(
                    liquidity
                )

        if not values:
            return None

        return min(
            values
        )

    # ========================================================
    # Success
    # ========================================================

    def _success(
        self,
        path,
        edges,
        cost,
        hop_count,
        total_fee,
        total_delay,
        path_reliability,
        total_distance,
        total_carbon,
        inter_country_hops,
        inter_continent_hops
    ):
        min_liquidity = (
            self._minimum_liquidity(
                edges
            )
        )

        return {

            "success": True,

            "path": list(
                path
            ),

            "edges": list(
                edges
            ),

            "cost": float(
                cost
            ),

            "hop_count": int(
                hop_count
            ),

            "total_fee": float(
                total_fee
            ),

            "total_delay": float(
                total_delay
            ),

            "min_liquidity": (
                None
                if min_liquidity is None
                else float(
                    min_liquidity
                )
            ),

            "reliability": float(
                path_reliability
            ),

            "failure_probability": float(
                1.0
                -
                path_reliability
            ),

            "total_distance_km": float(
                total_distance
            ),

            "total_carbon": float(
                total_carbon
            ),

            "inter_country_hops": int(
                inter_country_hops
            ),

            "inter_continent_hops": int(
                inter_continent_hops
            )
        }

    # ========================================================
    # Failure
    # ========================================================

    @staticmethod
    def _failure(
        reason="no_feasible_path"
    ):
        """
        Routing failure.

        This is a routing failure, not stochastic payment
        failure.
        """

        return {

            "success": False,

            "path": None,

            "edges": None,

            "cost": math.inf,

            "hop_count": 0,

            "total_fee": 0.0,

            "total_delay": 0.0,

            "min_liquidity": None,

            "reliability": 0.0,

            "failure_probability": 1.0,

            "total_distance_km": 0.0,

            "total_carbon": 0.0,

            "inter_country_hops": 0,

            "inter_continent_hops": 0,

            "reason": reason
        }

    # ========================================================
    # Numeric Helpers
    # ========================================================

    @staticmethod
    def _safe_float(
        value,
        default=0.0
    ):
        try:

            value = float(
                value
            )

            if not math.isfinite(
                value
            ):

                return float(
                    default
                )

            return value

        except (
            TypeError,
            ValueError
        ):

            return float(
                default
            )

    @staticmethod
    def _valid_number(
        value
    ):
        try:

            value = float(
                value
            )

            return math.isfinite(
                value
            )

        except (
            TypeError,
            ValueError
        ):

            return False

    @staticmethod
    def _valid_metric(
        value
    ):
        try:

            value = float(
                value
            )

            return (
                math.isfinite(
                    value
                )
                and
                value >= 0.0
            )

        except (
            TypeError,
            ValueError
        ):

            return False

    @staticmethod
    def _valid_cost(
        value
    ):
        """
        Dijkstra requires non-negative edge costs.
        """

        try:

            value = float(
                value
            )

            return (
                math.isfinite(
                    value
                )
                and
                value >= 0.0
            )

        except (
            TypeError,
            ValueError
        ):

            return False