# Pathfinding/test_eta.py

"""
Diagnostic eta sweep for the adaptive routing criterion.

This test verifies whether eta has an observable effect on the
routing objective before PPO training.

Important invariants:
    - k is ALWAYS fixed at 5.
    - eta is the only swept routing-control parameter.
    - source, destination and payment amount are fixed.
    - max_hops is fixed.
    - lambda_h is fixed.
    - a non-trivial pair with five feasible candidates is selected first.

Diagnostic levels:
    1. eta -> raw adaptive heuristic
    2. eta -> normalized adaptive penalty
    3. eta -> final adaptive edge cost
    4. eta -> candidate path cost
    5. eta -> Top-K ranking
    6. eta -> selected route

Run:
    py -m Pathfinding.test_eta
"""

import math

import networkx as nx
import numpy as np

from Pathfinding.top_k_paths import top_k_paths

from Pathfinding.heuristics import (
    adaptive_heuristic,
    adaptive_penalty,
    adaptive_edge_cost,
    lnd_cost,
)

from RL.test_rl import (
    CONFIG,
    GML_FILENAME,
    load_real_graph,
    prepare_graph,
    prepare_channel_attributes,
)


# ==========================================================
# TEST SETTINGS
# ==========================================================

ETA_VALUES = [
    round(float(x), 1)
    for x in np.arange(
        0.0,
        1.01,
        0.1,
    )
]

# ----------------------------------------------------------
# CRITICAL INVARIANT
# ----------------------------------------------------------

FIXED_K = 5

PAYMENT_AMOUNT = 1000

# Bounded deterministic search for a non-trivial test pair.
PAIR_SOURCE_LIMIT = 40
TARGETS_PER_SOURCE = 8

MIN_SEARCH_HOPS = 2
MAX_SEARCH_HOPS = 6


# ==========================================================
# FORMATTING HELPERS
# ==========================================================

def _fmt(value, digits=6):
    """
    Safe numeric formatter.
    """

    if value is None:
        return "None"

    try:
        value = float(value)

    except (
        TypeError,
        ValueError,
    ):
        return str(value)

    if not math.isfinite(value):
        return "nan"

    return f"{value:.{digits}f}"


# ==========================================================
# PATH SIGNATURE HELPERS
# ==========================================================

def _path_signature(candidate):
    """
    Return a hashable path signature.
    """

    return tuple(
        candidate.get(
            "path",
            [],
        )
    )


def _candidate_signature(candidates):
    """
    Return the ordered Top-K candidate signature.

    Order matters because the purpose of this test is to detect
    changes in candidate ranking.
    """

    return tuple(
        _path_signature(candidate)
        for candidate in candidates
    )


def _selected_path(candidates):
    """
    Return the currently selected candidate.

    top_k_paths() returns candidates ordered by routing cost,
    therefore candidates[0] is the selected route.
    """

    if not candidates:
        return None

    return candidates[0].get(
        "path"
    )


# ==========================================================
# CANDIDATE PRINT
# ==========================================================

def _print_candidate(
    rank,
    candidate,
):
    """
    Print one candidate route and its routing metrics.
    """

    print(
        f"  #{rank} "
        f"path={candidate.get('path')} "
        f"hops={candidate.get('hop_count')} "
        f"cost={_fmt(candidate.get('cost'))} "
        f"fee={_fmt(candidate.get('total_fee'))} "
        f"delay={_fmt(candidate.get('total_delay'))} "
        f"reliability={_fmt(candidate.get('reliability'))}"
    )

    print(
        f"      eta={_fmt(candidate.get('eta'))} "
        f"raw_heuristic={_fmt(candidate.get('raw_heuristic'))} "
        f"adaptive_penalty={_fmt(candidate.get('adaptive_penalty'))}"
    )

    print(
        f"      edges={candidate.get('edges')}"
    )


# ==========================================================
# TEST-PAIR DISCOVERY
# ==========================================================

def _build_pair_search_graph(G):
    """
    Build a simple directed graph only for discovering
    source/target pairs.

    The actual routing candidates are ALWAYS generated by
    top_k_paths() on the original prepared graph.
    """

    H = nx.DiGraph()

    H.add_nodes_from(
        G.nodes()
    )

    if G.is_multigraph():

        for u, v in G.edges():

            if u == v:
                continue

            if not H.has_edge(
                u,
                v,
            ):
                H.add_edge(
                    u,
                    v,
                )

    else:

        for u, v in G.edges():

            if u == v:
                continue

            H.add_edge(
                u,
                v,
            )

    return H


# ==========================================================
# GENERATE CANDIDATE SOURCE/TARGET PAIRS
# ==========================================================

def _candidate_pairs(G):
    """
    Generate deterministic non-trivial source/target pairs.

    High-degree nodes are tested first.

    Targets must be at least MIN_SEARCH_HOPS away and no farther
    than MAX_SEARCH_HOPS away.
    """

    H = _build_pair_search_graph(
        G
    )

    nodes_by_degree = sorted(
        H.nodes(),
        key=lambda node: (
            -H.degree(node),
            str(node),
        ),
    )

    sources = nodes_by_degree[
        :PAIR_SOURCE_LIMIT
    ]

    for source in sources:

        distances = (
            nx.single_source_shortest_path_length(
                H,
                source,
                cutoff=MAX_SEARCH_HOPS,
            )
        )

        targets = [
            node
            for node, distance in distances.items()
            if (
                node != source
                and
                MIN_SEARCH_HOPS
                <=
                distance
                <=
                MAX_SEARCH_HOPS
            )
        ]

        targets.sort(
            key=lambda node: (
                -H.degree(node),
                distances[node],
                str(node),
            )
        )

        for target in targets[
            :TARGETS_PER_SOURCE
        ]:

            yield (
                source,
                target,
                distances[target],
            )


# ==========================================================
# FIND TEST PAIR
# ==========================================================

def _find_test_pair(
    G,
    amount,
    max_hops,
    lambda_h,
):
    """
    Find one pair satisfying the eta-sweep requirements.

    Requirements:
        1. at least two hops;
        2. at least five feasible candidates at eta=0;
        3. k remains fixed at five.
    """

    print()
    print("=" * 54)
    print(" SEARCH FOR MULTI-CANDIDATE TEST PAIR")
    print("=" * 54)

    print(
        f"Required candidates : {FIXED_K}"
    )

    print(
        f"Payment amount      : {amount}"
    )

    print(
        f"Search hop range    : "
        f"{MIN_SEARCH_HOPS}..{max_hops}"
    )

    tested = 0

    for (
        source,
        target,
        distance,
    ) in _candidate_pairs(G):

        tested += 1

        candidates = top_k_paths(
            G=G,
            source=source,
            target=target,
            amount=amount,
            heuristic_fn=lnd_cost,
            eta=0.0,
            k=FIXED_K,
            max_hops=max_hops,
            lambda_h=lambda_h,
        )

        print(
            f"  Pair {tested:03d}: "
            f"{source} -> {target} "
            f"(unweighted_hops={distance}) "
            f"feasible_candidates="
            f"{len(candidates)}"
        )

        if (
            distance >= MIN_SEARCH_HOPS
            and
            len(candidates) >= FIXED_K
        ):

            print()
            print("FOUND TEST PAIR")

            print(
                f"  source           = {source}"
            )

            print(
                f"  destination      = {target}"
            )

            print(
                f"  unweighted hops  = {distance}"
            )

            print(
                f"  candidates eta=0 = "
                f"{len(candidates)}"
            )

            return (
                source,
                target,
            )

    raise RuntimeError(
        f"Could not find a pair with at least "
        f"{FIXED_K} feasible candidates."
    )


# ==========================================================
# CANDIDATE EDGES
# ==========================================================

def _candidate_edges(candidates):
    """
    Extract unique channel-level edges from candidate paths.
    """

    edges = []
    seen = set()

    for candidate in candidates:

        for edge in candidate.get(
            "edges",
            [],
        ):

            if len(edge) != 3:
                continue

            u, v, key = edge

            signature = (
                u,
                v,
                key,
            )

            if signature in seen:
                continue

            seen.add(
                signature
            )

            edges.append(
                signature
            )

    return edges


# ==========================================================
# READ EDGE DATA
# ==========================================================

def _get_edge_data(
    G,
    u,
    v,
    key,
):
    """
    Read the exact edge data associated with a candidate edge.

    Supports:
        Graph
        DiGraph
        MultiGraph
        MultiDiGraph
    """

    try:

        if G.is_multigraph():

            if key is not None:

                return dict(
                    G[u][v][key]
                )

            data = G[u][v]

            if not data:
                return None

            first_key = next(
                iter(data)
            )

            return dict(
                data[first_key]
            )

        return dict(
            G[u][v]
        )

    except (
        KeyError,
        TypeError,
        AttributeError,
    ):

        return None


# ==========================================================
# HEURISTIC / PENALTY / EDGE-COST SENSITIVITY
# ==========================================================

def _print_heuristic_sensitivity(
    G,
    candidates,
    amount,
    lambda_h,
):
    """
    Isolate:

        eta
          |
          +--> raw heuristic
          |
          +--> normalized penalty
          |
          +--> final adaptive edge cost

    This test does NOT require the final route ranking to change.
    """

    print()
    print("=" * 54)
    print(" ETA -> HEURISTIC -> PENALTY -> EDGE COST")
    print("=" * 54)

    edges = _candidate_edges(
        candidates
    )

    if not edges:

        print(
            "No candidate edges available."
        )

        return {
            "heuristic_changed": False,
            "penalty_changed": False,
            "cost_changed": False,
        }

    any_heuristic_changed = False
    any_penalty_changed = False
    any_cost_changed = False

    # Limit output while preserving deterministic behavior.
    sample_edges = edges[:10]

    print(
        f"Testing {len(sample_edges)} representative "
        f"candidate edges."
    )

    for index, (
        u,
        v,
        key,
    ) in enumerate(
        sample_edges,
        start=1,
    ):

        data = _get_edge_data(
            G,
            u,
            v,
            key,
        )

        if data is None:

            print(
                f"\nedge #{index}: "
                f"({u}, {v}, {key})"
            )

            print(
                "  Could not read edge data."
            )

            continue

        rows = []

        for eta in (
            0.0,
            0.5,
            1.0,
        ):

            raw_h = adaptive_heuristic(
                G,
                u,
                v,
                eta,
            )

            penalty = adaptive_penalty(
                G,
                u,
                v,
                eta,
            )

            edge_info = adaptive_edge_cost(
                G=G,
                u=u,
                v=v,
                data=data,
                amount=amount,
                eta=eta,
                heuristic_fn=lnd_cost,
                lambda_h=lambda_h,
            )

            rows.append(
                {
                    "eta": eta,
                    "raw_h": raw_h,
                    "penalty": penalty,
                    "native_cost": edge_info[
                        "native_cost"
                    ],
                    "cost": edge_info[
                        "cost"
                    ],
                }
            )

        raw_values = [
            row["raw_h"]
            for row in rows
        ]

        penalty_values = [
            row["penalty"]
            for row in rows
        ]

        cost_values = [
            row["cost"]
            for row in rows
        ]

        heuristic_changed = not (
            math.isclose(
                raw_values[0],
                raw_values[1],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
            and
            math.isclose(
                raw_values[1],
                raw_values[2],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
        )

        penalty_changed = not (
            math.isclose(
                penalty_values[0],
                penalty_values[1],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
            and
            math.isclose(
                penalty_values[1],
                penalty_values[2],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
        )

        cost_changed = not (
            math.isclose(
                cost_values[0],
                cost_values[1],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
            and
            math.isclose(
                cost_values[1],
                cost_values[2],
                rel_tol=1e-12,
                abs_tol=1e-12,
            )
        )

        any_heuristic_changed |= (
            heuristic_changed
        )

        any_penalty_changed |= (
            penalty_changed
        )

        any_cost_changed |= (
            cost_changed
        )

        print()
        print(
            f"edge #{index}: "
            f"({u}, {v}, {key})"
        )

        for row in rows:

            print(
                f"  eta={row['eta']:.1f} "
                f"raw_h={_fmt(row['raw_h'])} "
                f"penalty={_fmt(row['penalty'])} "
                f"native={_fmt(row['native_cost'])} "
                f"cost={_fmt(row['cost'])}"
            )

        print(
            "  status: "
            f"heuristic="
            f"{'CHANGED' if heuristic_changed else 'UNCHANGED'}, "
            f"penalty="
            f"{'CHANGED' if penalty_changed else 'UNCHANGED'}, "
            f"cost="
            f"{'CHANGED' if cost_changed else 'UNCHANGED'}"
        )

    print()
    print("-" * 54)

    print(
        "HEURISTIC EFFECT : "
        + (
            "CHANGED"
            if any_heuristic_changed
            else "UNCHANGED"
        )
    )

    print(
        "PENALTY EFFECT   : "
        + (
            "CHANGED"
            if any_penalty_changed
            else "UNCHANGED"
        )
    )

    print(
        "EDGE COST EFFECT : "
        + (
            "CHANGED"
            if any_cost_changed
            else "UNCHANGED"
        )
    )

    return {
        "heuristic_changed":
            any_heuristic_changed,

        "penalty_changed":
            any_penalty_changed,

        "cost_changed":
            any_cost_changed,
    }


# ==========================================================
# CANDIDATE COST COMPARISON
# ==========================================================

def _print_cost_response(
    results,
):
    """
    Show how candidate path costs respond to eta.

    The path itself may remain unchanged while its cost changes.
    """

    print()
    print("=" * 54)
    print(" ETA EFFECT ON CANDIDATE PATH COSTS")
    print("=" * 54)

    for eta, candidates in results:

        print()
        print(
            f"ETA = {eta:.1f}"
        )

        for rank, candidate in enumerate(
            candidates,
            start=1,
        ):

            print(
                f"  #{rank} "
                f"cost={_fmt(candidate.get('cost'))} "
                f"raw_h={_fmt(candidate.get('raw_heuristic'))} "
                f"penalty={_fmt(candidate.get('adaptive_penalty'))} "
                f"path={candidate.get('path')}"
            )


# ==========================================================
# ETA RANKING SUMMARY
# ==========================================================

def _print_change_summary(results):
    """
    Compare candidate ordering and selected route across eta.

    Ranking change and selected-route change are reported
    independently.
    """

    print()
    print("=" * 54)
    print(" ETA EFFECT SUMMARY")
    print("=" * 54)

    previous_eta = None
    previous_signature = None

    ranking_change_count = 0

    for eta, candidates in results:

        signature = _candidate_signature(
            candidates
        )

        if previous_signature is None:

            status = "BASELINE"

        elif signature != previous_signature:

            status = "CHANGED"
            ranking_change_count += 1

        else:

            status = "UNCHANGED"

        print(
            f"eta={eta:.1f} "
            f"status={status:<9} "
            f"count={len(candidates)} "
            f"selected={_selected_path(candidates)}"
        )

        if (
            previous_eta is not None
            and
            signature != previous_signature
        ):

            print(
                f"  ranking changed: "
                f"eta {previous_eta:.1f} "
                f"-> {eta:.1f}"
            )

        previous_eta = eta
        previous_signature = signature

    unique_rankings = {
        _candidate_signature(
            candidates
        )
        for _, candidates in results
    }

    unique_selected = {
        tuple(
            _selected_path(
                candidates
            )
            or []
        )
        for _, candidates in results
    }

    print()

    print(
        f"Number of eta transitions with "
        f"candidate-order change: "
        f"{ranking_change_count}"
    )

    print(
        f"Unique candidate rankings observed: "
        f"{len(unique_rankings)}"
    )

    print(
        f"Unique selected routes observed: "
        f"{len(unique_selected)}"
    )

    print()

    if len(unique_rankings) == 1:

        print(
            "ROUTING DIAGNOSIS: eta did NOT change "
            "the Top-5 candidate ranking for this pair."
        )

    else:

        print(
            "ROUTING DIAGNOSIS: eta DOES change "
            "the Top-5 candidate ranking."
        )

    if len(unique_selected) == 1:

        print(
            "SELECTED ROUTE DIAGNOSIS: "
            "the selected route remained unchanged."
        )

    else:

        print(
            "SELECTED ROUTE DIAGNOSIS: "
            "the selected route changed."
        )

    return {
        "unique_rankings":
            len(unique_rankings),

        "unique_selected":
            len(unique_selected),

        "ranking_change_count":
            ranking_change_count,
    }


# ==========================================================
# FIXED-K CHECK
# ==========================================================

def _check_fixed_k(
    results,
):
    """
    Verify that every eta returns exactly K candidates.

    If this invariant fails, the eta sweep is considered invalid.
    """

    print()
    print("=" * 54)
    print(" FIXED-K CHECK")
    print("=" * 54)

    for eta, candidates in results:

        if len(candidates) != FIXED_K:

            raise AssertionError(
                f"k invariant violated at "
                f"eta={eta:.1f}: "
                f"got {len(candidates)}, "
                f"expected {FIXED_K}"
            )

        print(
            f"eta={eta:.1f}: "
            f"{len(candidates)} candidates "
            f"(K fixed at {FIXED_K})"
        )


# ==========================================================
# FINAL DIAGNOSIS
# ==========================================================

def _print_final_diagnosis(
    sensitivity,
    ranking_summary,
):
    """
    Produce a compact scientific diagnosis.

    Important:
        Ranking stability does NOT imply that eta is ineffective.
        The cost signal can change while the order of the five
        routes remains unchanged.
    """

    print()
    print("=" * 54)
    print(" FINAL ETA DIAGNOSIS")
    print("=" * 54)

    print(
        "eta -> raw heuristic : "
        + (
            "PASS"
            if sensitivity["heuristic_changed"]
            else "FAIL"
        )
    )

    print(
        "eta -> penalty       : "
        + (
            "PASS"
            if sensitivity["penalty_changed"]
            else "FAIL"
        )
    )

    print(
        "eta -> edge cost     : "
        + (
            "PASS"
            if sensitivity["cost_changed"]
            else "FAIL"
        )
    )

    print(
        f"Unique rankings      : "
        f"{ranking_summary['unique_rankings']}"
    )

    print(
        f"Unique selected paths: "
        f"{ranking_summary['unique_selected']}"
    )

    print()

    if not sensitivity["heuristic_changed"]:

        print(
            "RESULT: eta has no observable effect on "
            "the adaptive heuristic for the tested edges."
        )

        print(
            "ACTION: inspect node carbon attributes and "
            "adaptive_heuristic()."
        )

        return

    if not sensitivity["penalty_changed"]:

        print(
            "RESULT: the raw heuristic changes, but the "
            "normalized adaptive penalty does not change."
        )

        print(
            "ACTION: inspect the normalization scale "
            "inside adaptive_penalty()."
        )

        return

    if not sensitivity["cost_changed"]:

        print(
            "RESULT: the adaptive penalty changes, but "
            "the final edge cost does not change."
        )

        print(
            "ACTION: inspect lambda_h and adaptive_edge_cost()."
        )

        return

    if ranking_summary["unique_rankings"] > 1:

        print(
            "RESULT: eta has an observable effect on "
            "the routing objective AND changes Top-K ranking."
        )

    else:

        print(
            "RESULT: eta changes the routing objective, "
            "but Top-K ranking remained stable for this pair."
        )

        print(
            "This is NOT evidence that eta is broken."
        )

        print(
            "The five candidate paths can preserve their "
            "relative ordering even when their costs change."
        )


# ==========================================================
# MAIN
# ==========================================================

def main():

    print()
    print("=" * 54)
    print(" ETA SWEEP DIAGNOSTIC")
    print(f" Snapshot: {GML_FILENAME}")
    print(f" Fixed K: {FIXED_K}")
    print(
        f" Payment amount: {PAYMENT_AMOUNT}"
    )
    print("=" * 54)

    # ------------------------------------------------------
    # 1. Load real GML
    # ------------------------------------------------------

    G = load_real_graph()

    # ------------------------------------------------------
    # 2. Prepare graph
    # ------------------------------------------------------

    G = prepare_graph(
        G
    )

    G = prepare_channel_attributes(
        G
    )

    print()
    print("Prepared graph:")

    print(
        f"  type  = {type(G).__name__}"
    )

    print(
        f"  nodes = {G.number_of_nodes()}"
    )

    print(
        f"  edges = {G.number_of_edges()}"
    )

    # ------------------------------------------------------
    # 3. Read fixed routing parameters
    # ------------------------------------------------------

    lambda_h = float(
        CONFIG["graph"].get(
            "lambda_h",
            1.0,
        )
    )

    max_hops = int(
        CONFIG["graph"].get(
            "max_hops",
            12,
        )
    )

    print()
    print("Fixed routing parameters:")

    print(
        f"  K        = {FIXED_K}"
    )

    print(
        f"  amount   = {PAYMENT_AMOUNT}"
    )

    print(
        f"  max_hops = {max_hops}"
    )

    print(
        f"  lambda_h = {lambda_h}"
    )

    print(
        "  eta      = 0.0 .. 1.0"
    )

    # ------------------------------------------------------
    # 4. Find one multi-path pair
    # ------------------------------------------------------

    source, target = _find_test_pair(
        G=G,
        amount=PAYMENT_AMOUNT,
        max_hops=max_hops,
        lambda_h=lambda_h,
    )

    print()
    print("=" * 54)
    print(" FIXED TEST TRANSACTION")
    print("=" * 54)

    print(
        f"  source      = {source}"
    )

    print(
        f"  destination = {target}"
    )

    print(
        f"  amount      = {PAYMENT_AMOUNT}"
    )

    print(
        f"  K           = {FIXED_K}"
    )

    # ------------------------------------------------------
    # 5. Sweep eta on the SAME pair
    # ------------------------------------------------------

    results = []

    print()
    print("=" * 54)
    print(" ETA SWEEP")
    print("=" * 54)

    for eta in ETA_VALUES:

        print()
        print("-" * 54)

        print(
            f"ETA = {eta:.1f}   K = {FIXED_K}"
        )

        print(
            "-" * 54
        )

        candidates = top_k_paths(
            G=G,
            source=source,
            target=target,
            amount=PAYMENT_AMOUNT,
            heuristic_fn=lnd_cost,
            eta=eta,
            k=FIXED_K,
            max_hops=max_hops,
            lambda_h=lambda_h,
        )

        # --------------------------------------------------
        # Fixed-K invariant
        # --------------------------------------------------

        if len(candidates) != FIXED_K:

            raise AssertionError(
                f"eta={eta:.1f} returned "
                f"{len(candidates)} candidates; "
                f"expected exactly K={FIXED_K}."
            )

        results.append(
            (
                eta,
                candidates,
            )
        )

        print(
            f"Candidate count = "
            f"{len(candidates)}"
        )

        for rank, candidate in enumerate(
            candidates,
            start=1,
        ):

            _print_candidate(
                rank,
                candidate,
            )

    # ------------------------------------------------------
    # 6. Verify fixed K
    # ------------------------------------------------------

    _check_fixed_k(
        results
    )

    # ------------------------------------------------------
    # 7. Isolate eta -> heuristic / penalty / cost
    # ------------------------------------------------------

    sensitivity = (
        _print_heuristic_sensitivity(
            G=G,
            candidates=results[0][1],
            amount=PAYMENT_AMOUNT,
            lambda_h=lambda_h,
        )
    )

    # ------------------------------------------------------
    # 8. Show candidate cost response
    # ------------------------------------------------------

    _print_cost_response(
        results
    )

    # ------------------------------------------------------
    # 9. Compare rankings
    # ------------------------------------------------------

    ranking_summary = (
        _print_change_summary(
            results
        )
    )

    # ------------------------------------------------------
    # 10. Final diagnosis
    # ------------------------------------------------------

    _print_final_diagnosis(
        sensitivity=sensitivity,
        ranking_summary=ranking_summary,
    )

    print()
    print("=" * 54)
    print(" ETA SWEEP COMPLETED")
    print("=" * 54)


# ==========================================================
# ENTRY POINT
# ==========================================================

if __name__ == "__main__":
    main()