# Pathfinding/test_eta.py

"""
Diagnostic eta sweep for the adaptive routing criterion.

This test verifies whether PPO's action (eta) has an observable effect
on the routing objective before PPO training.

Important invariants:
    - k is ALWAYS fixed at 5.
    - eta is the only swept routing-control parameter.
    - the same source, destination and payment amount are used for all eta.
    - a non-trivial pair with five feasible candidates is selected first.

Run:
    py -m Pathfinding.test_eta
"""

import math

import networkx as nx
import numpy as np

from Pathfinding.top_k_paths import top_k_paths
from Pathfinding.heuristics import adaptive_heuristic, lnd_cost

from RL.test_rl import (
    CONFIG,
    GML_FILENAME,
    load_real_graph,
    prepare_graph,
    prepare_channel_attributes,
)


# ==========================================================
# TEST SETTINGS
# ==========================================================

ETA_VALUES = [
    round(float(x), 1)
    for x in np.arange(0.0, 1.01, 0.1)
]

FIXED_K = 5

PAYMENT_AMOUNT = 1000

# Bounded deterministic search for a non-trivial test pair.
PAIR_SOURCE_LIMIT = 40
TARGETS_PER_SOURCE = 8

MIN_SEARCH_HOPS = 2
MAX_SEARCH_HOPS = 6


# ==========================================================
# FORMATTING / SIGNATURE HELPERS
# ==========================================================

def _fmt(value, digits=6):
    if value is None:
        return "None"

    try:
        value = float(value)
    except (TypeError, ValueError):
        return str(value)

    if not math.isfinite(value):
        return "nan"

    return f"{value:.{digits}f}"


def _path_signature(candidate):
    return tuple(
        candidate.get("path", [])
    )


def _candidate_signature(candidates):
    return tuple(_path_signature(c) for c in candidates)


def _selected_path(candidates):
    if not candidates:
        return None
    return candidates[0].get("path")


# ==========================================================
# CANDIDATE PRINT
# ==========================================================

def _print_candidate(rank, candidate):

    print(
        f"  #{rank} "
        f"path={candidate.get('path')} "
        f"hops={candidate.get('hop_count')} "
        f"cost={_fmt(candidate.get('cost'))} "
        f"fee={_fmt(candidate.get('total_fee'))} "
        f"delay={_fmt(candidate.get('total_delay'))} "
        f"reliability={_fmt(candidate.get('reliability'))}"
    )

    if "raw_heuristic" in candidate:

        print(
            f"      raw_heuristic={_fmt(candidate.get('raw_heuristic'))} "
            f"adaptive_penalty={_fmt(candidate.get('adaptive_penalty'))}"
        )

    print(
        f"      eta={_fmt(candidate.get('eta'))} "
        f"edges={candidate.get('edges')}"
    )


# ==========================================================
# TEST-PAIR DISCOVERY
# ==========================================================

def _build_pair_search_graph(G):
    """
    Build a simple directed graph only for discovering source/target
    pairs.

    The actual routing candidates are ALWAYS generated by top_k_paths()
    on the original prepared graph.
    """
    H = nx.DiGraph()

    H.add_nodes_from(G.nodes())

    if G.is_multigraph():

        for u, v in G.edges():

            if u == v:
                continue

            if not H.has_edge(u, v):
                H.add_edge(u, v)

    else:

        for u, v in G.edges():

            if u == v:
                continue

            H.add_edge(u, v)

    return H


# ==========================================================
# GENERATE CANDIDATE SOURCE/TARGET PAIRS
# ==========================================================

def _candidate_pairs(G):
    """
    Generate deterministic non-trivial source/target pairs.

    High-degree nodes are tested first. Targets must be at least
    MIN_SEARCH_HOPS away and no farther than MAX_SEARCH_HOPS away.
    """
    H = _build_pair_search_graph(G)

    # High-degree nodes are checked first.
    nodes_by_degree = sorted(
        H.nodes(),
        key=lambda node: (-H.degree(node), str(node)),
    )

    sources = nodes_by_degree[
        :PAIR_SOURCE_LIMIT
    ]

    for source in sources:

        distances = (
            nx.single_source_shortest_path_length(
                H,
                source,
                cutoff=MAX_SEARCH_HOPS,
            )
        )

        targets = [
            node
            for node, distance in distances.items()
            if (
                node != source
                and MIN_SEARCH_HOPS <= distance <= MAX_SEARCH_HOPS
            )
        ]

        targets.sort(
            key=lambda node: (
                -H.degree(node),
                distances[node],
                str(node),
            )
        )

        for target in targets[:TARGETS_PER_SOURCE]:
            yield source, target, distances[target]


def _find_test_pair(G, amount, max_hops, lambda_h):
    """
    Find one pair with exactly the conditions required for the eta test:

        1. at least two hops;
        2. at least five feasible candidates;
        3. k remains fixed at five.
    """
    print(
        "
"
        "======================================================"
    )
    print(" SEARCH FOR MULTI-CANDIDATE TEST PAIR")
    print(
        "======================================================"
    )
    print(f"Required candidates : {FIXED_K}")
    print(f"Payment amount      : {amount}")
    print(
        f"Search hop range    : "
        f"{MIN_SEARCH_HOPS}..{max_hops}"
    )

    tested = 0

    for (
        source,
        target,
        distance,
    ) in _candidate_pairs(G):

        tested += 1

        candidates = top_k_paths(
            G=G,
            source=source,
            target=target,
            amount=amount,
            heuristic_fn=lnd_cost,
            eta=0.0,
            k=FIXED_K,
            max_hops=max_hops,
            lambda_h=lambda_h,
        )

        print(
            f"  Pair {tested:03d}: "
            f"{source} -> {target} "
            f"(unweighted_hops={distance}) "
            f"feasible_candidates="
            f"{len(candidates)}"
        )

        if (
            distance >= MIN_SEARCH_HOPS
            and
            len(candidates) >= FIXED_K
        ):
            print("
FOUND TEST PAIR")
            print(f"  source      = {source}")
            print(f"  destination = {target}")
            print(f"  unweighted hops = {distance}")
            print(
                f"  candidates at eta=0 = "
                f"{len(candidates)}"
            )

            return source, target

    raise RuntimeError(
        f"Could not find a pair with at least "
        f"{FIXED_K} feasible candidates."
    )


# ==========================================================
# HEURISTIC SENSITIVITY CHECK
# ==========================================================

def _candidate_edges(candidates):

    edges = []
    seen = set()

    for candidate in candidates:

        for edge in candidate.get(
            "edges",
            [],
        ):

            if len(edge) != 3:
                continue

            u, v, key = edge

            signature = (
                u,
                v,
                key,
            )

            if signature in seen:
                continue

            seen.add(signature)
            edges.append(signature)

    return edges


def _print_heuristic_sensitivity(G, candidates):
    """
    Isolate eta -> adaptive_heuristic() from eta -> route ranking.
    """
    print(
        "
"
        "======================================================"
    )
    print(" HEURISTIC SENSITIVITY CHECK")
    print("=" * 54)

    edges = _candidate_edges(
        candidates
    )

    if not edges:

        print(
            "No candidate edges available."
        )

        return False

    changed = False

    for index, (
        u,
        v,
        key,
    ) in enumerate(
        edges,
        start=1,
    ):

        values = []

        for eta in (
            0.0,
            0.5,
            1.0,
        ):

            value = adaptive_heuristic(
                G,
                u,
                v,
                eta,
            )

            values.append(value)

        edge_changed = not (
            math.isclose(values[0], values[1], rel_tol=1e-12, abs_tol=1e-12)
            and
            math.isclose(values[1], values[2], rel_tol=1e-12, abs_tol=1e-12)
        )

        changed = changed or edge_changed

        status = (
            "CHANGED"
            if edge_changed
            else "UNCHANGED"
        )

        print(
            f"edge #{index}: "
            f"({u}, {v}, {key}) "
            f"h(0.0)={_fmt(values[0])} "
            f"h(0.5)={_fmt(values[1])} "
            f"h(1.0)={_fmt(values[2])} "
            f"status={'CHANGED' if edge_changed else 'UNCHANGED'}"
        )

    print()

    if changed:

        print(
            "
HEURISTIC DIAGNOSIS: eta changes the adaptive "
            "heuristic on at least one candidate edge."
        )

    else:

        print(
            "
HEURISTIC DIAGNOSIS: eta does NOT change the "
            "adaptive heuristic on the tested candidate edges."
        )

        print(
            "Inspect node attributes and "
            "adaptive_heuristic() before PPO training."
        )

    return changed


# ==========================================================
# ETA RANKING SUMMARY
# ==========================================================

def _print_change_summary(results):
    print(
        "
"
        "======================================================"
    )
    print(" ETA EFFECT SUMMARY")
    print("=" * 54)

    previous_eta = None
    previous_signature = None

    changed_count = 0

    for eta, candidates in results:

        signature = _candidate_signature(
            candidates
        )

        if previous_signature is None:

            status = "BASELINE"

        elif signature != previous_signature:

            status = "CHANGED"

            changed_count += 1

        else:

            status = "UNCHANGED"

        print(
            f"eta={eta:.1f} "
            f"status={status:<9} "
            f"count={len(candidates)} "
            f"selected={_selected_path(candidates)}"
        )

        if (
            previous_eta is not None
            and
            signature != previous_signature
        ):
            print(
                f"  ranking changed: "
                f"eta {previous_eta:.1f} -> {eta:.1f}"
            )

        previous_eta = eta
        previous_signature = signature

    unique_rankings = {
        _candidate_signature(candidates)
        for _, candidates in results
    }

    unique_selected = {
        tuple(
            _selected_path(candidates)
            or []
        )
        for _, candidates in results
    }

    print()

    print()
    print(
        f"
Number of eta transitions with "
        f"candidate-order change: {changed_count}"
    )
    print(
        f"Unique candidate rankings observed: "
        f"{len(unique_rankings)}"
    )
    print(
        f"Unique selected routes observed: "
        f"{len(unique_selected)}"
    )

    if len(unique_rankings) == 1:
        print(
            "
ROUTING DIAGNOSIS: eta did NOT change the "
            "top-5 candidate ranking for this multi-path pair."
        )

    else:
        print(
            "
ROUTING DIAGNOSIS: eta DOES change the "
            "top-5 candidate ranking."
        )


def main():
    print(
        "
"
        "======================================================"
    )
    print(" ETA SWEEP DIAGNOSTIC")
    print(f" Snapshot: {GML_FILENAME}")
    print(f" Fixed K: {FIXED_K}")
    print(f" Payment amount: {PAYMENT_AMOUNT}")
    print(
        "======================================================"
    )

    # ------------------------------------------------------
    # 1. Load and prepare real GML
    # ------------------------------------------------------

    G = load_real_graph()

    # ------------------------------------------------------
    # 2. Prepare graph
    # ------------------------------------------------------

    G = prepare_graph(G)

    G = prepare_channel_attributes(G)

    print("
Prepared graph:")
    print(f"  type  = {type(G).__name__}")
    print(f"  nodes = {G.number_of_nodes()}")
    print(f"  edges = {G.number_of_edges()}")

    # ------------------------------------------------------
    # 2. Routing parameters
    # ------------------------------------------------------

    lambda_h = float(
        CONFIG["graph"].get(
            "lambda_h",
            1.0,
        )
    )

    max_hops = int(
        CONFIG["graph"].get(
            "max_hops",
            12,
        )
    )

    # ------------------------------------------------------
    # 3. Find one real multi-path pair
    # ------------------------------------------------------

    source, target = _find_test_pair(
        G=G,
        amount=PAYMENT_AMOUNT,
        max_hops=max_hops,
        lambda_h=lambda_h,
    )

    print()
    print("=" * 54)
    print(" FIXED TEST TRANSACTION")
    print("=" * 54)

    print(
        f"  source      = {source}"
    )

    print(
        f"  destination = {target}"
    )

    print(
        "
"
        "======================================================"
    )
    print(" FIXED TEST TRANSACTION")
    print(
        "======================================================"
    )
    print(f"  source      = {source}")
    print(f"  destination = {target}")
    print(f"  amount      = {PAYMENT_AMOUNT}")
    print(f"  k           = {FIXED_K}")

    # ------------------------------------------------------
    # 4. Sweep eta on the SAME pair
    # ------------------------------------------------------

    results = []

    print()
    print("=" * 54)
    print(" ETA SWEEP")
    print("=" * 54)

    for eta in ETA_VALUES:
        print(
            "
------------------------------------------------------"
        )
        print(
            f"ETA = {eta:.1f}   K = {FIXED_K}"
        )
        print(
            "------------------------------------------------------"
        )

        candidates = top_k_paths(
            G=G,
            source=source,
            target=target,
            amount=PAYMENT_AMOUNT,
            heuristic_fn=lnd_cost,
            eta=eta,
            k=FIXED_K,
            max_hops=max_hops,
            lambda_h=lambda_h,
        )

        # The selected test pair was required to have five feasible
        # candidates. If this changes during the sweep, the test is
        # invalid rather than silently accepting fewer candidates.
        if len(candidates) != FIXED_K:

            raise AssertionError(
                f"eta={eta:.1f} returned "
                f"{len(candidates)} candidates; "
                f"expected exactly K={FIXED_K}."
            )

        results.append(
            (eta, candidates)
        )

        print(
            f"  Candidate count = {len(candidates)}"
        )

        for rank, candidate in enumerate(
            candidates,
            start=1,
        ):
            _print_candidate(
                rank,
                candidate,
            )

    # ------------------------------------------------------
    # 5. Isolate eta -> heuristic effect
    # ------------------------------------------------------

    _print_heuristic_sensitivity(
        G,
        results[0][1],
    )

    # ------------------------------------------------------
    # 6. Compare rankings and selected routes
    # ------------------------------------------------------

    _print_change_summary(results)

    # ------------------------------------------------------
    # 7. Fixed-K invariant
    # ------------------------------------------------------

    print(
        "
"
        "======================================================"
    )
    print(" FIXED-K CHECK")
    print("=" * 54)

    for eta, candidates in results:

        if len(candidates) != FIXED_K:

            raise AssertionError(
                f"k invariant violated at "
                f"eta={eta:.1f}: "
                f"got {len(candidates)}, "
                f"expected {FIXED_K}"
            )

        print(
            f"eta={eta:.1f}: {len(candidates)} candidates "
            f"(K fixed at {FIXED_K})"
        )

    print()
    print("ETA SWEEP COMPLETED")


# ==========================================================
# ENTRY POINT
# ==========================================================

if __name__ == "__main__":
    main()