# Pathfinding/top_k_paths.py

import math
import networkx as nx

from .heuristics import (
    lnd_cost,
    adaptive_heuristic,
    modified_cost,
    channel_fee,
    reliability_penalty,
)


# ==========================================================
# Learned / Observed Directional Liquidity
# ==========================================================

def _estimated_liquidity(data):
    """
    Return learned/observed directional liquidity.

    Priority:
        1. estimated_liquidity
        2. liquidity_uv
        3. balance_uv

    Important:
        capacity is NOT interpreted as liquidity.
        Unknown liquidity is returned as None.
    """

    for field in (
        "estimated_liquidity",
        "liquidity_uv",
        "balance_uv",
    ):
        if field not in data:
            continue

        value = data.get(field)

        if value is None:
            continue

        try:
            value = float(value)
        except (TypeError, ValueError):
            continue

        if math.isfinite(value) and value >= 0.0:
            return value

    return None


# ==========================================================
# Channel Feasibility
# ==========================================================

def _channel_can_carry(data, amount):
    """
    Check known directional liquidity.

    liquidity < amount
        -> channel is rejected

    liquidity >= amount
        -> channel is accepted

    liquidity unknown
        -> channel is accepted

    Actual payment feasibility is evaluated later by
    FailureModel / PaymentSimulator.
    """

    liquidity = _estimated_liquidity(data)

    if liquidity is None:
        return True

    return liquidity >= float(amount)


# ==========================================================
# Channel Reliability
# ==========================================================

def _channel_reliability(data):
    """
    Estimate forwarding reliability.

    Priority:
        1. success/failure history
        2. failure_probability
        3. default failure probability = 0.01
    """

    success = _safe_float(
        data.get("success_count", 0)
    )

    failure = _safe_float(
        data.get("failure_count", 0)
    )

    total = success + failure

    if total > 0:
        failure_probability = failure / total

    elif "failure_probability" in data:
        failure_probability = _safe_float(
            data.get("failure_probability"),
            default=0.01,
        )

    else:
        failure_probability = 0.01

    failure_probability = min(
        max(failure_probability, 0.0),
        1.0,
    )

    return 1.0 - failure_probability


# ==========================================================
# Edge Cost
# ==========================================================

def _adaptive_edge_cost(
    G,
    u,
    v,
    data,
    amount,
    eta,
    heuristic_fn=None,
    lambda_h=1.0,
):
    """
    Calculate adaptive routing cost.

    Native cost:

        C_LND(e)

    Adaptive heuristic:

        h(u,v)

    Modified cost:

        C'(e) = C_LND(e) + lambda_h * h(u,v)

    eta is generated by PPO and passed to adaptive_heuristic().
    """

    # ------------------------------------------------------
    # Native routing cost
    # ------------------------------------------------------

    if heuristic_fn is not None:
        try:
            native_cost = heuristic_fn(
                G,
                u,
                v,
                data,
                amount,
            )
        except (
            TypeError,
            ValueError,
            KeyError,
        ):
            native_cost = lnd_cost(
                G,
                u,
                v,
                data,
                amount,
            )
    else:
        native_cost = lnd_cost(
            G,
            u,
            v,
            data,
            amount,
        )

    if not _valid_cost(native_cost):
        return None

    # ------------------------------------------------------
    # Adaptive heuristic
    # ------------------------------------------------------

    try:
        h = adaptive_heuristic(
            G,
            u,
            v,
            eta,
        )
    except (
        TypeError,
        ValueError,
        KeyError,
    ):
        h = 0.0

    if not _valid_number(h):
        return None

    # ------------------------------------------------------
    # Modified cost
    # ------------------------------------------------------

    try:
        cost = modified_cost(
            native_cost=float(native_cost),
            geo_penalty=float(h),
            eta=float(eta),
            lambda_h=float(lambda_h),
        )
    except (
        TypeError,
        ValueError,
        KeyError,
    ):
        return None

    if not _valid_cost(cost):
        return None

    return float(cost)


# ==========================================================
# Build Routing Graph
# ==========================================================

def _build_routing_graph(
    G,
    amount,
    eta,
    max_hops,
    heuristic_fn=None,
    lambda_h=1.0,
):
    """
    Build a simplified directed graph for node-level
    candidate route generation.

    The original graph may be a MultiDiGraph with parallel
    Lightning channels.

    For each directed node pair (u,v), the cheapest usable
    channel is retained.

    The original channel key and channel data are preserved.
    """

    H = nx.DiGraph()

    # ------------------------------------------------------
    # Copy nodes
    # ------------------------------------------------------

    for node, node_data in G.nodes(data=True):
        H.add_node(
            node,
            **dict(node_data),
        )

    # ------------------------------------------------------
    # Process channels
    # ------------------------------------------------------

    if isinstance(G, (nx.MultiGraph, nx.MultiDiGraph)):

        edge_iterator = G.edges(
            keys=True,
            data=True,
        )

        for u, v, key, raw_data in edge_iterator:

            data = dict(raw_data)

            # ----------------------------------------------
            # Channel availability
            # ----------------------------------------------

            if not bool(
                data.get(
                    "available",
                    True,
                )
            ):
                continue

            # ----------------------------------------------
            # Endpoint availability
            # ----------------------------------------------

            if not _node_available(G, u):
                continue

            if not _node_available(G, v):
                continue

            # ----------------------------------------------
            # Known directional liquidity
            # ----------------------------------------------

            if not _channel_can_carry(
                data,
                amount,
            ):
                continue

            # ----------------------------------------------
            # Adaptive cost
            # ----------------------------------------------

            weight = _adaptive_edge_cost(
                G=G,
                u=u,
                v=v,
                data=data,
                amount=amount,
                eta=eta,
                heuristic_fn=heuristic_fn,
                lambda_h=lambda_h,
            )

            if weight is None:
                continue

            # ----------------------------------------------
            # Channel metrics
            # ----------------------------------------------

            fee = channel_fee(
                data,
                amount,
            )

            if not _valid_metric(fee):
                continue

            delay = _channel_delay(data)

            if not _valid_metric(delay):
                continue

            reliability = _channel_reliability(data)

            if not _valid_metric(reliability):
                continue

            edge_attributes = {
                "weight": float(weight),
                "channel_key": key,
                "channel_data": data,
                "fee": float(fee),
                "delay": float(delay),
                "reliability": float(reliability),
                "eta": float(eta),
            }

            # ----------------------------------------------
            # Keep cheapest usable channel for node pair
            # ----------------------------------------------

            if not H.has_edge(u, v):

                H.add_edge(
                    u,
                    v,
                    **edge_attributes,
                )

            else:

                existing_weight = H[u][v]["weight"]

                if weight < existing_weight:
                    H[u][v].update(
                        edge_attributes
                    )

    else:

        # --------------------------------------------------
        # Support ordinary Graph / DiGraph as well.
        # --------------------------------------------------

        for u, v, raw_data in G.edges(data=True):

            data = dict(raw_data)

            if not bool(
                data.get(
                    "available",
                    True,
                )
            ):
                continue

            if not _node_available(G, u):
                continue

            if not _node_available(G, v):
                continue

            if not _channel_can_carry(
                data,
                amount,
            ):
                continue

            weight = _adaptive_edge_cost(
                G=G,
                u=u,
                v=v,
                data=data,
                amount=amount,
                eta=eta,
                heuristic_fn=heuristic_fn,
                lambda_h=lambda_h,
            )

            if weight is None:
                continue

            fee = channel_fee(
                data,
                amount,
            )

            if not _valid_metric(fee):
                continue

            delay = _channel_delay(data)

            if not _valid_metric(delay):
                continue

            reliability = _channel_reliability(data)

            if not _valid_metric(reliability):
                continue

            edge_attributes = {
                "weight": float(weight),
                "channel_key": data.get(
                    "channel_key",
                    None,
                ),
                "channel_data": data,
                "fee": float(fee),
                "delay": float(delay),
                "reliability": float(reliability),
                "eta": float(eta),
            }

            if (
                not H.has_edge(u, v)
                or
                weight < H[u][v]["weight"]
            ):
                H.add_edge(
                    u,
                    v,
                    **edge_attributes,
                )

    return H


# ==========================================================
# Complete Path Metrics
# ==========================================================

def _path_metrics(H, path):
    """
    Calculate aggregate candidate-path metrics.
    """

    total_cost = 0.0
    total_fee = 0.0
    total_delay = 0.0
    reliability = 1.0

    for u, v in zip(
        path[:-1],
        path[1:],
    ):
        edge = H[u][v]

        total_cost += _safe_float(
            edge.get("weight", 0.0)
        )

        total_fee += _safe_float(
            edge.get("fee", 0.0)
        )

        total_delay += _safe_float(
            edge.get("delay", 0.0)
        )

        edge_reliability = min(
            max(
                _safe_float(
                    edge.get(
                        "reliability",
                        1.0,
                    )
                ),
                0.0,
            ),
            1.0,
        )

        reliability *= edge_reliability

    return {
        "cost": float(total_cost),
        "total_fee": float(total_fee),
        "total_delay": float(total_delay),
        "reliability": float(reliability),
        "failure_probability": float(
            1.0 - reliability
        ),
    }


# ==========================================================
# Convert Node Path to Channel Path
# ==========================================================

def _path_edges(H, path):
    """
    Convert a node path into exact channel edges:

        (u, v, channel_key)

    The selected original channel key is preserved.
    """

    edges = []

    for u, v in zip(
        path[:-1],
        path[1:],
    ):
        key = H[u][v].get(
            "channel_key"
        )

        edges.append(
            (
                u,
                v,
                key,
            )
        )

    return edges


# ==========================================================
# Validate Candidate Route
# ==========================================================

def _valid_candidate_path(
    path,
    source,
    target,
    max_hops,
):
    """
    Validate a node-level candidate path.
    """

    if not isinstance(
        path,
        (list, tuple),
    ):
        return False

    if len(path) < 2:
        return False

    if path[0] != source:
        return False

    if path[-1] != target:
        return False

    hops = len(path) - 1

    if hops > max_hops:
        return False

    # Simple path: no repeated nodes.
    if len(set(path)) != len(path):
        return False

    return True


# ==========================================================
# K Candidate Routes
# ==========================================================

def top_k_paths(
    G,
    source,
    target,
    amount,
    heuristic_fn=None,
    eta=0.0,
    k=10,
    max_hops=12,
    lambda_h=1.0,
):
    """
    Generate K candidate routing paths.

    Pipeline:

        Network State
              |
              v
             PPO
              |
              v
             eta
              |
              v
      Adaptive Heuristic
              |
              v
       Modified Edge Cost
              |
              v
       K Candidate Paths
              |
              v
            Bucket
              |
              v
       Payment Simulation

    Returns
    -------
    list of dict

        Each candidate contains:

            path
            edges
            cost
            hop_count
            total_fee
            total_delay
            reliability
            failure_probability
            eta
            lambda_h
            candidate
            success

    Important
    ---------
    candidate=True means the route was generated by the
    routing layer.

    It does NOT mean that the payment will succeed.
    Actual payment success is determined later by
    FailureModel / PaymentSimulator.
    """

    # ======================================================
    # Basic validation
    # ======================================================

    if source == target:
        return []

    if source not in G:
        return []

    if target not in G:
        return []

    try:
        amount = float(amount)
    except (
        TypeError,
        ValueError,
    ):
        return []

    if (
        not math.isfinite(amount)
        or
        amount <= 0.0
    ):
        return []

    try:
        k = int(k)
    except (
        TypeError,
        ValueError,
    ):
        return []

    if k <= 0:
        return []

    try:
        max_hops = int(max_hops)
    except (
        TypeError,
        ValueError,
    ):
        return []

    if max_hops <= 0:
        return []

    try:
        eta = float(eta)
    except (
        TypeError,
        ValueError,
    ):
        raise ValueError(
            "eta must be numeric"
        )

    if not math.isfinite(eta):
        raise ValueError(
            "eta must be finite"
        )

    if not -1.0 <= eta <= 1.0:
        raise ValueError(
            f"eta must be in [-1, 1], got {eta}"
        )

    try:
        lambda_h = float(lambda_h)
    except (
        TypeError,
        ValueError,
    ):
        raise ValueError(
            "lambda_h must be numeric"
        )

    if (
        not math.isfinite(lambda_h)
        or
        lambda_h < 0.0
    ):
        raise ValueError(
            "lambda_h must be finite and >= 0"
        )

    # ======================================================
    # Build simplified routing graph
    # ======================================================

    H = _build_routing_graph(
        G=G,
        amount=amount,
        eta=eta,
        max_hops=max_hops,
        heuristic_fn=heuristic_fn,
        lambda_h=lambda_h,
    )

    if (
        source not in H
        or
        target not in H
    ):
        return []

    # ======================================================
    # Candidate generation
    # ======================================================

    try:
        path_generator = nx.shortest_simple_paths(
            H,
            source,
            target,
            weight="weight",
        )
    except (
        nx.NetworkXNoPath,
        nx.NodeNotFound,
    ):
        return []

    results = []
    seen_paths = set()

    try:

        for path in path_generator:

            # ------------------------------------------------
            # Validate path
            # ------------------------------------------------

            if not _valid_candidate_path(
                path,
                source,
                target,
                max_hops,
            ):
                continue

            path_tuple = tuple(path)

            if path_tuple in seen_paths:
                continue

            seen_paths.add(path_tuple)

            # ------------------------------------------------
            # Convert path to exact channel edges
            # ------------------------------------------------

            edges = _path_edges(
                H,
                path,
            )

            if len(edges) != len(path) - 1:
                continue

            # ------------------------------------------------
            # Aggregate metrics
            # ------------------------------------------------

            metrics = _path_metrics(
                H,
                path,
            )

            # ------------------------------------------------
            # Candidate
            # ------------------------------------------------

            candidate = {
                "path": list(path),

                "edges": edges,

                "cost": metrics["cost"],

                "hop_count": int(
                    len(path) - 1
                ),

                "total_fee": metrics[
                    "total_fee"
                ],

                "total_delay": metrics[
                    "total_delay"
                ],

                "reliability": metrics[
                    "reliability"
                ],

                "failure_probability": metrics[
                    "failure_probability"
                ],

                "eta": float(eta),

                "lambda_h": float(
                    lambda_h
                ),

                "candidate": True,

                # PaymentSimulator will update this.
                "success": None,
            }

            results.append(candidate)

            if len(results) >= k:
                break

    except nx.NetworkXNoPath:
        pass

    # ======================================================
    # Explicit ranking
    # ======================================================

    results.sort(
        key=lambda item: (
            item["cost"],
            item["hop_count"],
            item["total_fee"],
            -item["reliability"],
        )
    )

    return results


# ==========================================================
# Channel Delay
# ==========================================================

def _channel_delay(data):
    """
    Extract channel delay.

    Supported attributes:

        delay
        cltv_expiry_delta
    """

    return _safe_float(
        data.get(
            "delay",
            data.get(
                "cltv_expiry_delta",
                0.0,
            ),
        )
    )


# ==========================================================
# Node Availability
# ==========================================================

def _node_available(G, node):
    """
    Check node availability.

    Both attributes are supported:

        available
        is_online
    """

    if node not in G:
        return False

    data = G.nodes[node]

    if not bool(
        data.get(
            "available",
            True,
        )
    ):
        return False

    if not bool(
        data.get(
            "is_online",
            True,
        )
    ):
        return False

    return True


# ==========================================================
# Numeric Helpers
# ==========================================================

def _safe_float(
    value,
    default=0.0,
):
    try:

        value = float(value)

        if not math.isfinite(value):
            return float(default)

        return value

    except (
        TypeError,
        ValueError,
    ):
        return float(default)


def _valid_number(value):
    try:

        value = float(value)

        return math.isfinite(value)

    except (
        TypeError,
        ValueError,
    ):
        return False


def _valid_metric(value):
    try:

        value = float(value)

        return (
            math.isfinite(value)
            and
            value >= 0.0
        )

    except (
        TypeError,
        ValueError,
    ):
        return False


def _valid_cost(value):
    """
    Dijkstra / shortest-simple-path algorithms require
    non-negative edge weights.
    """

    try:

        value = float(value)

        return (
            math.isfinite(value)
            and
            value >= 0.0
        )

    except (
        TypeError,
        ValueError,
    ):
        return False